apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc-nodeport
spec: 
  selector: 
    app: jupyter
    project: fine_tuning
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 30880
    name: jupyter-port
  type: NodePort