apiVersion: v1
kind: Service
metadata:
  name: llm-train-svc
spec:
  selector:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/node-type: head
  ports:
  - port: 80
    targetPort: 8000
    name: serve
  - port: 8265
    targetPort: 8265
    name: dashboard
    nodePort: 32265
  type: NodePort